name: Package Application with Pyinstaller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: Collection2PresetWindows.py
          options: --onefile

      - uses: actions/upload-artifact@v2
        with:
          name: packaged-exe
          path: dist/Collection2PresetWindows.exe
